project:
  type: book
  output-dir: docs

book:
  title: "Sistema de reporte de avances"
  author: "Samuel Calderon"
  chapters:
    - index.qmd
    - chap-login/index.qmd
    - chap-user/index.qmd
    - references.qmd
  appendices: 
    - chap-appendix/index.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
    lang: es
    css: styles.css
    fig-align: center
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto



