project:
  type: book
  output-dir: docs

book:
  title: "Sistema de reporte de avances"
  author: "Samuel Calderon"
  chapters:
    - index.qmd
    - manual-user.qmd
    - manual-admin.qmd
    # - references.qmd
  appendices: 
    - zzz-task-lifecycle.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
    lang: es
    css: styles.css
    fig-align: center
  pdf:
    documentclass: scrreprt
  docx: default  
  
execute:
  freeze: auto



